name: Deploy code

on:
  push:
    branches:
      - develop
      - test
      - main

permissions:
      contents: read

jobs:

  Deployment:
    uses: ./.github/workflows/salesforce-ci-reusable.yml
    with:
      environment: ${{  github.ref_name == 'develop' && 'develop' || github.ref_name == 'test' && 'SIT' || startsWith(github.ref_name, 'release/') && 'UAT' }}
      action_type: 'deploy'
    secrets: inherit
