name: salesforce-ci
# This workflow allows manual deployment of changes to a Salesforce org.
# It is triggered manually or can eb called by a different workflow and allows the user to specify the environment, and whether to validate or deploy changes.
# The workflow uses the sfdx-git-delta plugin to generate a delta of changes and then
# deploys or validates those changes against the specified Salesforce org.

on:
  workflow_dispatch: 
    inputs:
        environment:
          description: 'Environment to run tests against'
          required: true
          default: 'Development'
        action_type:
          description: 'Select whether to validate or deploy changes'
          required: true
          default: 'validate'
          type: choice
          options:
            - validate
            - deploy
  workflow_call:
    inputs:
      action_type:
        required: true
        type: string
      environment:
        required: true
        type: string
  
jobs:
  ManualDeployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: ${{ inputs.environment }}
    env:
        SFDX_URL: ${{ secrets.SFDX_URL }}
        API_VERSION: ${{ vars.API_VERSION }}
        FROM_TAG: ${{ vars.FROM_TAG }}  
        TO_TAG: ${{ vars.TO_TAG }}
        SANDBOX_NAME: ${{ vars.SANDBOX_NAME }}
        RUNAGAINSTORG: ${{ vars.RUNAGAINSTORG }}
        UNITTESTS_SCOPE: ${{ vars.UNITTESTS_SCOPE }}
        SPECIFIEDTESTS: ${{ vars.testclassnames }}
        SF_CLI_URL: ${{ vars.SF_CLI_URL }}
        ENCRYPTED_KEY: ${{ secrets.ENCRYPTED_KEY }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        AESKEY: ${{ secrets.AESKEY }}
        IVKEY: ${{ secrets.IVKEY }}
        INSTANCE_URL: ${{ vars.INSTANCE_URL }}
        
    steps:
      # checkout Source
      - name: 'Checkout source code'
        uses: actions/checkout@v6.0.2 # V6.0.2
        with:
          fetch-depth: 0


      # Install Salesforce CLI via pnpm
      - name: Install Salesforce CLI
        run: npm add -g @salesforce/cli${{vars.SF_CLI_VERSION}}

      # conform SF version
      - name: Verify Salesforce CLI
        run: |
          sf --version
     

      #Authorizes the salesforce environment and deploys or validates changes in the Salesforce org
      - name: Authorize Org
        run: |
          bash scripts/pipelines/AuthorizeOrg.sh
      - name: 🚀 Start Action
        run: |
          bash scripts/pipelines/DeployOrValidateToOrg.sh ${{ inputs.action_type}}