name: Validation

on:
  pull_request:
    branches:
      - develop
      - test
      - main

jobs:

  Validate:
    uses: ./.github/workflows/manual-deployment.yml
    with:
      environment: ${{  github.base_ref == 'develop' && 'develop' || github.base_ref == 'test' && 'SIT' || startsWith(github.base_ref, 'refs/heads/release/') && 'UAT'|| github.base_ref == 'main' && 'Production' }}
      action_type: 'validate'
    secrets: inherit
